#!/bin/sh

# Adapted from https://autotools.info/pkgconfig/cross-compiling.html

SYSROOT=/opt/raspberrypi_rootfs

# ensure pkg-config no longer looks in the host machine and it looks inside the sysroot insteadf
# these folders contain the .pc files inside the sysroot
export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${SYSROOT}/usr/share/pkgconfig

# clear this - we don't want the paths re-routed, especially if found outside of the sysroot
export PKG_CONFIG_SYSROOT_DIR=

# ensure these paths are pruned from the output flags
export PKG_CONFIG_SYSTEM_LIBRARY_PATH=/usr/lib:/usr/lib/aarch64-linux-gnu
export PKG_CONFIG_SYSTEM_INCLUDE_PATH=/usr/include:/usr/include/aarch64-linux-gnu

# forward the call to the real pkg-config
exec /usr/bin/pkg-config "$@" 


